import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import apiClient from '../api/client';

export interface RecurringRule {
  id: string;
  description: string;
  amount: string;
  type: 'INCOME' | 'EXPENSE';
  frequency: 'WEEKLY' | 'MONTHLY';
  paymentMethod: 'CASH' | 'CARD' | 'BANK_TRANSFER' | 'OTHER';
  currency: string;
  startDate: string;
  endDate: string | null;
  nextDueDate: string;
  lastGeneratedDate: string | null;
  status: 'ACTIVE' | 'PAUSED';
  maxBackfillMonths: number;
  createdAt: string;
  updatedAt: string;
  userId: string;
  categoryId: string;
  category: {
    id: string;
    name: string;
    icon: string;
    color: string;
  };
}

export interface CreateRuleData {
  description: string;
  amount: string;
  type: 'INCOME' | 'EXPENSE';
  categoryId: string;
  frequency: 'WEEKLY' | 'MONTHLY';
  paymentMethod?: 'CASH' | 'CARD' | 'BANK_TRANSFER' | 'OTHER';
  currency?: string;
  startDate: string;
  endDate?: string;
}

export interface UpdateRuleData {
  description?: string;
  amount?: string;
  type?: 'INCOME' | 'EXPENSE';
  categoryId?: string;
  frequency?: 'WEEKLY' | 'MONTHLY';
  paymentMethod?: 'CASH' | 'CARD' | 'BANK_TRANSFER' | 'OTHER';
  currency?: string;
  startDate?: string;
  endDate?: string | null;
  status?: 'ACTIVE' | 'PAUSED';
}

export interface PendingTransaction {
  id: string;
  amount: string;
  type: 'INCOME' | 'EXPENSE';
  description: string | null;
  date: string;
  paymentMethod: string;
  currency: string;
  isAutoGenerated: boolean;
  isConfirmed: boolean;
  recurringRuleId: string | null;
  categoryId: string;
  category: {
    id: string;
    name: string;
    icon: string;
    color: string;
  };
}

const INVALIDATE_KEYS = ['recurring-rules', 'pending-transactions', 'transactions', 'analytics/summary', 'analytics/trends', 'budgets'];

function invalidateRelated(queryClient: ReturnType<typeof useQueryClient>) {
  INVALIDATE_KEYS.forEach((key) => {
    queryClient.invalidateQueries({ queryKey: [key] });
  });
}

export function useRecurringRules() {
  return useQuery({
    queryKey: ['recurring-rules'],
    queryFn: async () => {
      const { data } = await apiClient.get('/recurring-rules');
      return data.data as RecurringRule[];
    },
  });
}

export function usePendingTransactions() {
  return useQuery({
    queryKey: ['pending-transactions'],
    queryFn: async () => {
      const { data } = await apiClient.get('/recurring-rules/pending');
      return data.data as PendingTransaction[];
    },
  });
}

export function useGeneratePending() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async () => {
      const { data } = await apiClient.post('/recurring-rules/generate');
      return data.data;
    },
    onSuccess: () => invalidateRelated(queryClient),
  });
}

export function useCreateRule() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (body: CreateRuleData) => {
      const { data } = await apiClient.post('/recurring-rules', body);
      return data.data;
    },
    onSuccess: () => invalidateRelated(queryClient),
  });
}

export function useUpdateRule() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, ...body }: UpdateRuleData & { id: string }) => {
      const { data } = await apiClient.put(`/recurring-rules/${id}`, body);
      return data.data;
    },
    onSuccess: () => invalidateRelated(queryClient),
  });
}

export function useDeleteRule() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { data } = await apiClient.delete(`/recurring-rules/${id}`);
      return data.data;
    },
    onSuccess: () => invalidateRelated(queryClient),
  });
}

export function useSkipNext() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { data } = await apiClient.post(`/recurring-rules/${id}/skip`);
      return data.data;
    },
    onSuccess: () => invalidateRelated(queryClient),
  });
}

export function useConfirmTransaction() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { data } = await apiClient.post(`/recurring-rules/confirm/${id}`);
      return data.data;
    },
    onSuccess: () => invalidateRelated(queryClient),
  });
}

export function useDismissTransaction() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { data } = await apiClient.post(`/recurring-rules/dismiss/${id}`);
      return data.data;
    },
    onSuccess: () => invalidateRelated(queryClient),
  });
}

export function useConfirmAllPending() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async () => {
      const { data } = await apiClient.post('/recurring-rules/confirm-all');
      return data.data;
    },
    onSuccess: () => invalidateRelated(queryClient),
  });
}
